// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOXRvCE-sCqlPUh3BP8mKHg0TikOrwUEU',
    appId: '1:635505254366:web:d7794fb41192a99876074f',
    messagingSenderId: '635505254366',
    projectId: 'tram-doc-app',
    authDomain: 'tram-doc-app.firebaseapp.com',
    storageBucket: 'tram-doc-app.firebasestorage.app',
    measurementId: 'G-DZT7KZY253',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFXQQr7GOvkb9udxJNcxr2jg_p2IkP7to',
    appId: '1:635505254366:android:4bf1fe51393a827476074f',
    messagingSenderId: '635505254366',
    projectId: 'tram-doc-app',
    storageBucket: 'tram-doc-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Xh_-to6jbczlyNaUZrAzFgYPFyWunCY',
    appId: '1:635505254366:ios:0d85b9488dfe849376074f',
    messagingSenderId: '635505254366',
    projectId: 'tram-doc-app',
    storageBucket: 'tram-doc-app.firebasestorage.app',
    iosBundleId: 'com.example.tramdoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8Xh_-to6jbczlyNaUZrAzFgYPFyWunCY',
    appId: '1:635505254366:ios:0d85b9488dfe849376074f',
    messagingSenderId: '635505254366',
    projectId: 'tram-doc-app',
    storageBucket: 'tram-doc-app.firebasestorage.app',
    iosBundleId: 'com.example.tramdoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOXRvCE-sCqlPUh3BP8mKHg0TikOrwUEU',
    appId: '1:635505254366:web:7bb90d78a58132c876074f',
    messagingSenderId: '635505254366',
    projectId: 'tram-doc-app',
    authDomain: 'tram-doc-app.firebaseapp.com',
    storageBucket: 'tram-doc-app.firebasestorage.app',
    measurementId: 'G-TGRNJYMBMR',
  );
}
